### ISSUE TITLE
Drop support for Elixir 1.11

### ISSUE THREAD

**Issue by philss** [philss/floki#462]
Since we are approaching the release of Elixir 1.15, and we have OTP 26 recently released, we should
drop support for Elixir 1.11.

## Tasks

* [ ] Update the `.github/workflows` files.
* [ ] Update `mix.exs`.
* [ ] Ensure everything is working / tests are passing.
* [ ] Release a new version.
